name: Github Pages

on:
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    name: Build & Deploy Github Pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        rm yarn.lock
        npm i -g yarn
        yarn

    - name: Build
      run: |
        yarn build

    - name: Initialise Git repository
      run: |
        git config --global user.name 'Kinetix-Lee'
        git config --global user.email 'i@x86.app'
        git config --global init.defaultBranch 'master'
        cd ./dist && git init && git add .
        git commit -m "CI Deployed $(date)"

    - name: Deploy to GitHub Pages
      env:
        GITHUB_REPO: github.com/Kinetix-Lee/time.git
      run: |
        git push --force "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:gh-pages 